### ISSUE TITLE
Demo doesn't exist

### ISSUE THREAD

**Issue by ahogen** [christianmendoza/hugo-smpl-theme#1]
Both the README here and the [themes.hugo.io](https://themes.gohugo.io/hugo-smpl-theme/) page say that [http://themes.gohugo.io/theme/hugo-smpl-theme/](http://themes.gohugo.io/theme/hugo-smpl-theme/) is a demo site for this theme, but that URL is dead...

**Comment by christianmendoza** [comment]
Thanks for this heads up. Just updated the readme with the new demo url:

https://hugo-smpl-theme.netlify.com
