### ISSUE TITLE
how to change icon size

### ISSUE THREAD

**Issue by Trree** [christianmendoza/hugo-smpl-theme#2]
I want to change icon size, 
so I change icon = "fa-dribbble fa-5x" In the config.toml,
but it don't change the size of icon.
How can I change icon size by config.toml.

**Comment by christianmendoza** [comment]
I straight ported this template. It looks like the icon sizes are set in the main.css and overriding font-awesome. I haven't tested this but at quick glance if you remove the font-size in /static/assets/css/main.css and add "fa-dribbble fa-5x" in config.toml you should be good.

```
.w i {
	/* font-size: 26px; */
	padding: 12px;
}
```
